# 项目相关配置
nyc:
  # 名称
  name: nyc
  # 版本
  version: ${revision}
  # 版权年份
  copyrightYear: 2022
#spring
spring:
  application:
    name: nyc

  profiles:
    active: dev

  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
  #    lazy-initialization: true  # 配置为true 表示所有Bean 都将延迟初始化
  jmx:
    enabled: false   #默认会开启 JMX，可以使用 jconsole 查看，对于我们无需这些监控的话可以手动关闭它。

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER #解决 SpringFox 与 SpringBoot 2.6.x 不兼容的问题，参见 SpringFoxHandlerProviderBeanPostProcessor 类

    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true

  resources:
    #不要为我们工程中的资源文件建立映射
    add-mappings: false



  # Servlet 配置
  servlet:
    # 文件上传相关配置项
    multipart:
      max-file-size: 16MB # 单个文件大小
      max-request-size: 32MB # 设置总上传的文件大小

#  # Jackson 配置项
#  jackson:
#    serialization:
#      write-dates-as-timestamps: true # 设置 Date 的格式，使用时间戳
#      write-date-timestamps-as-nanoseconds: false # 设置不使用 nanoseconds 的格式。例如说 1611460870.401，而是直接 1611460870401
#      write-durations-as-timestamps: true # 设置 Duration 的格式，使用时间戳
#      fail-on-empty-beans: false # 允许序列化无属性的 Bean

# MyBatis Plus 的配置项
mybatis-plus:
  # 不支持多包, 如有需要可在注解配置 或 提升扫包等级
  # 例如 com.**.**.mapper
  mapperPackage: com.git.bds.nyc.**.mapper
  # 对应的 XML 文件位置
  mapperLocations: classpath*:mapper/*Xml.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.git.bds.nyc.**.domain
  # 启动时是否检查 MyBatis XML 文件的存在，默认不检查
  checkConfigLocation: false
  configuration:
    call-setters-on-nulls: true                             #如果map查出字段为空，也显示
    #org.apache.ibatis.logging.stdout.StdOutImpl 控制台打印sql语句方便调试sql语句执行错误
    #org.apache.ibatis.logging.log4j2.Log4j2Impl:这个不在控制台打印查询结果,但是在log4j中打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # MyBatis 自动映射时未知列或未知属性处理策
    # NONE：不做处理 WARNING：打印相关警告 FAILING：抛出异常和详细信息
    autoMappingUnknownColumnBehavior: NONE
    # 自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
  global-config:
    # 是否打印 Logo banner
    banner: true
    db-config:
      # 主键类型
      # AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      idType: ASSIGN_ID
      # 逻辑已删除值
      logicDeleteValue: 0
      # 逻辑未删除值
      logicNotDeleteValue: -1
      # 字段验证策略之 insert,在 insert 的时候的字段验证策略
      # IGNORED 忽略 NOT_NULL 非NULL NOT_EMPTY 非空 DEFAULT 默认 NEVER 不加入 SQL
      insertStrategy: NOT_NULL
      # 字段验证策略之 update,在 update 的时候的字段验证策略
      updateStrategy: NOT_NULL
      # 字段验证策略之 select,在 select 的时候的字段验证策略既 wrapper 根据内部 entity 生成的 where 条件
      where-strategy: NOT_NULL

# MinIO 配置
minio:
  endpoint: http://82.157.157.133:9000      # MinIO服务地址
  fileHost: http://82.157.157.133:9000      # 文件地址host
  bucketName: img                      # 存储桶bucket名称
  accessKey: admin                         # 用户名
  secretKey: 12345678                     # 密码
  imgSize: 2                           # 图片大小限制，单位：m
  fileSize: 20                          # 文件大小限制，单位：m

#微信小程序
wx:
  miniapp:
    configs:
      - appid: wx2b1b9f396a67b94c  #微信小程序的appid
        secret: b76856231c6db17c47e3e88779c95889 #微信小程序的Secret
        token: bigdatastudio666 #微信小程序消息服务器配置的token
        aesKey: 38iWpSLrffHLNdw1740GiZlYFIIZL5Kjd1hYSvmfhtF #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON

# es
easy-es:
  enable: true #默认为true,若为false则认为不启用本框架
  address : 82.157.157.133:9200 # es的连接地址,必须含端口 若为集群,则可以用逗号隔开 例如:127.0.0.1:9200,127.0.0.2:9200
  banner: false # 默认为true 打印banner 若您不期望打印banner,可配置为false
  # 拓展配置
  keep-alive-millis: 18000 # 心跳策略时间 单位:ms
  connectTimeout: 5000 # 连接超时时间 单位:ms
  socketTimeout: 5000 # 通信超时时间 单位:ms
  requestTimeout: 5000 # 请求超时时间 单位:ms
  connectionRequestTimeout: 5000 # 连接请求超时时间 单位:ms
  maxConnTotal: 100 # 最大连接数 单位:个
  maxConnPerRoute: 100 # 最大连接路由数 单位:个
  # 全局配置
  db-config:
    map-underscore-to-camel-case: false # 是否开启下划线转驼峰 默认为false
    table-prefix: daily_ # 索引前缀,可用于区分环境  默认为空 用法和MP一样
    id-type: customize # id生成策略 customize为自定义,id值由用户生成,比如取MySQL中的数据id,如缺省此项配置,则id默认策略为es自动生成
    field-strategy: not_empty # 字段更新策略 默认为not_null
    enable-track-total-hits: true # 默认开启,查询若指定了size超过1w条时也会自动开启,开启后查询所有匹配数据,若不开启,会导致无法获取数据总条数,其它功能不受影响.
    refresh-policy: immediate # 数据刷新策略,默认为不刷新
    enable-must2-filter: false # 是否全局开启must查询类型转换为filter查询类型 默认为false不转换

knife4j:
  # 开启增强配置
  enable: true
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: test
    # Basic认证密码
    password: 123
  cors: true
  info:
    # 标题
    title: '农营C 接口文档'
    # 描述
    description: '农营C 线上农作物交易平台'
    # 版本
    version: '${nyc.version}'
    # 作者信息
    contact:
      name: 成大事
      email: 17337995232@qq.com
      url: https://blog.chengdashi.cn/

# 开启防xss
mica:
  xss:
    enabled: true

#logging:
#  config: classpath:log4j2.yml
