spring:
  profiles:
    active: dev

## MinIO 配置
#minio:
#  endpoint: http://82.157.157.133:9000      # MinIO服务地址
#  fileHost: http://82.157.157.133:9000      # 文件地址host
#  bucketName: img                      # 存储桶bucket名称
#  accessKey: admin                         # 用户名
#  secretKey: 12345678                     # 密码
#  imgSize: 1024                           # 图片大小限制，单位：m
#  fileSize: 1024                          # 文件大小限制，单位：m

knife4j:
  # 开启增强配置
  enable: true
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: test
    # Basic认证密码
    password: 123
  cors: true
# 开启防xss
mica:
  xss:
    enabled: true
# 微信小程序
wx:
  miniapp:
    configs:
      - appid: wx2b1b9f396a67b94c  #微信小程序的appid
        secret: b76856231c6db17c47e3e88779c95889 #微信小程序的Secret
        token: bigdatastudio666 #微信小程序消息服务器配置的token
        aesKey: 38iWpSLrffHLNdw1740GiZlYFIIZL5Kjd1hYSvmfhtF #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
#logging:
#  config: classpath:log4j2.yml